[pytest]
# фильтры предупреждений, чтобы сделать вывод чище
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::UserWarning

# -ra: показать дополнительную информацию о тестах
# -q: тихий режим
addopts = -ra -q

# указывает pytest, где искать тесты
testpaths = tests